### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by Kalle801** [fredfishgames/MatchmakerForUnity#1]
Hello. I create the config file and added it to the other matchmaker files. I still can not connect, whats wrong?

fredfishgames matchmaking server for unity
Licenced under the MIT licence
Make sure the configuration file has been set up before starting
[1mStarting Overpowered matchmaking server on port 24713[0m
[92mPlayer connected from 127.0.0.1[0m
Recieved request b'POST '
Invalid command.
Sent response
Closing thread

**Comment by fredfishgames** [comment]
Hi,
Have you customized the code in any way, and if so, can you make sure that the data sent follows [this](https://github.com/fredfishgames/MatchmakerForUnity/blob/master/Server/matchmaking-server-python/Codes.md)

The config file is embedded in `server.py`, as the multiline string.
Please note that this is not secure, fully featured in any way, and not designed to be used in a commercial release. I also do not work on the project anymore, and I will likely not update it in the future. If you would like a fully-featured server, I would recommend turning to a game backend service like PlayFab or Gamesparks, or the built in unity matchmaker. Or you can modify and build upon my code.

If you send me any of your files that work with the matchmaker, I will do my best to resolve any other problems you have.
